### PR TITLE
Possible re-edit after commit 6b13876 to samples/wasm/CMakeLists.txt as it breaks tiny sample build on Linux

### PR DESCRIPTION
**Pull request by KaivalyaD**
samples/wasm/CMakeLists.txt adds a demo sourced from Tiny.cpp, but the actual file is named tiny.cpp, which caused building issues for the tiny sample:

[`add_demo("Tiny" "${IGL_ROOT_DIR}/samples/wasm/igl.html")`](https://github.com/facebook/igl/blob/6b13876d28c3600b2908205247306ff1a164f979/samples/wasm/CMakeLists.txt#L25C57-L25C57)

[PS: Hi! It is my very first time contributing to open source. If you've got time, please share if I should or should not have included something in this description. Thanks!]

### CODE REVIEW

**Comment by EricGriffith** [comment]
Unfortunately we can't handle file renames that just change the case of the filename. You'll need to fix the CMake files instead.

**Comment by KaivalyaD** [comment]
Thanks, I've changed the cmake file instead

**Comment by KaivalyaD** [comment]
This issue might have arose because Win32 ignores filename cases while others (I am using linux) aren't so forgiving. Seems to have caused quite nasty issues in the past:

https://stackoverflow.com/questions/33998669/windows-ntfs-and-case-sensitivity
https://stackoverflow.com/questions/59393782/cmake-adding-case-insensitive-source-files

**Comment by corporateshark** [comment]
Fixed in https://github.com/facebook/igl/commit/f5289e26644d82f5a12796b7f169239ed6acfd16

**Pull request closed without merging**
